# Generated by Django 5.2.6 on 2025-09-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('errorCode', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('tableID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('manufacturer', models.TextField(max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
                ('speed', models.FloatField()),
                ('status', models.CharField(max_length=16)),
                ('anomalies', models.BinaryField(max_length=1)),
                ('activationCounter', models.PositiveIntegerField()),
                ('sitStandCounter', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=128)),
                ('passwordHash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('errorCode', models.SmallIntegerField()),
                ('errorTime', models.DateTimeField(auto_now_add=True)),
                ('tableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tables')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('MultipleObjectsReturned', models.AutoField(primary_key=True, serialize=False)),
                ('preferredPosition', models.PositiveSmallIntegerField()),
                ('timeFrom', models.DateTimeField()),
                ('timeTo', models.DateTimeField()),
                ('profileName', models.CharField(max_length=32)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
