# Generated by Django 5.2.6 on 2025-09-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_errors_errorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwordHash',
            field=models.BinaryField(max_length=32),
        ),
    ]
