# Generated by Django 5.2.6 on 2025-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_passwordhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adminStatus',
            field=models.BinaryField(default=1, max_length=1),
        ),
    ]
